// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertChirp = `-- name: InsertChirp :one
INSERT INTO chirp (id, created_at, update_at, body, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
returning id, created_at, update_at, body, user_id
`

type InsertChirpParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) InsertChirp(ctx context.Context, arg InsertChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, insertChirp, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdateAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
